import type { VisualNode } from '../types';

/**
 * PRE-BUILT INDIAN SEDUCTRESS CONCEPT NODES
 *
 * These are complete, ready-to-use concepts centered around Indian Seductress models.
 * Clicking one button auto-selects all related nodes and configures the full shot.
 *
 * Organized by intimacy/seduction level (1-12 range primarily)
 */

export const seductressConceptNodes: VisualNode[] = [
  // LEVEL 4-6: EDITORIAL CONFIDENCE
  {
    id: 'concept-power-exec',
    category: 'concept',
    name: 'Power Executive',
    abbreviation: 'EXEC',
    icon: '👔',
    color: '#8B5CF6',
    shape: 'circle',
    effects: {
      intimacy: [4, 6],
      seduction: [5, 7],
      eroticism: [4, 6],
      professionalism: [5, 7],
      power: [8, 10],
      boundary: [4, 6],
    },
    description: 'Indian Seductress in boardroom power suit, unbuttoned blazer, commanding presence',
    compatibleWith: ['subject-seductress', 'wardrobe-power-suit', 'pose-confident-allure', 'env-corporate', 'weave-passion'],
  },
  {
    id: 'concept-fashion-editorial',
    category: 'concept',
    name: 'Fashion Editorial',
    abbreviation: 'FASH',
    icon: '📸',
    color: '#8B5CF6',
    shape: 'circle',
    effects: {
      intimacy: [5, 7],
      seduction: [6, 8],
      eroticism: [5, 7],
      professionalism: [6, 8],
      abstraction: [6, 8],
      boundary: [5, 7],
    },
    description: 'High-fashion editorial with dramatic lighting and bold wardrobe',
    compatibleWith: ['subject-seductress', 'wardrobe-asymmetric-wrap', 'pose-confident-allure', 'env-fashion-studio', 'light-editorial'],
  },

  // LEVEL 7-9: SENSUAL SOPHISTICATION
  {
    id: 'concept-glamour-vintage',
    category: 'concept',
    name: 'Vintage Glamour',
    abbreviation: 'GLAM',
    icon: '🎀',
    color: '#9333EA',
    shape: 'circle',
    effects: {
      intimacy: [7, 9],
      seduction: [8, 10],
      eroticism: [7, 9],
      professionalism: [8, 10],
      boundary: [7, 9],
    },
    description: 'Classic pin-up style with vintage corset, Hollywood glamour lighting',
    compatibleWith: ['subject-seductress', 'wardrobe-vintage-corset', 'pose-confident-allure', 'env-fashion-studio', 'style-editorial'],
  },
  {
    id: 'concept-silk-elegance',
    category: 'concept',
    name: 'Silk Elegance',
    abbreviation: 'SILK',
    icon: '💃',
    color: '#9333EA',
    shape: 'circle',
    effects: {
      intimacy: [7, 9],
      seduction: [8, 10],
      eroticism: [7, 9],
      professionalism: [8, 10],
      boundary: [7, 9],
    },
    description: 'Flowing silk slip dress, soft intimate lighting, editorial sophistication',
    compatibleWith: ['subject-seductress', 'wardrobe-silk-slip', 'pose-confident-allure', 'env-private-loft', 'light-studio-soft'],
  },

  // LEVEL 8-10: ARTISTIC SEDUCTION
  {
    id: 'concept-architectural-form',
    category: 'concept',
    name: 'Architectural Form',
    abbreviation: 'ARCH',
    icon: '⚡',
    color: '#A855F7',
    shape: 'circle',
    effects: {
      intimacy: [9, 11],
      seduction: [9, 11],
      eroticism: [9, 11],
      professionalism: [10, 12],
      abstraction: [12, 14],
      boundary: [9, 11],
    },
    description: 'Geometric harness creating sculptural patterns, chiaroscuro lighting',
    compatibleWith: ['subject-super-seductress', 'wardrobe-geometric-harness', 'pose-seductive-invitation', 'env-private-loft', 'light-chiaroscuro'],
  },
  {
    id: 'concept-cultural-fusion',
    category: 'concept',
    name: 'Cultural Fusion',
    abbreviation: 'CULT',
    icon: '🪷',
    color: '#A855F7',
    shape: 'circle',
    effects: {
      intimacy: [8, 10],
      seduction: [9, 11],
      eroticism: [8, 10],
      professionalism: [9, 11],
      abstraction: [9, 11],
      boundary: [8, 10],
    },
    description: 'Sensual sari drape meets modern photography, traditional-contemporary blend',
    compatibleWith: ['subject-seductress', 'wardrobe-sari-drape', 'pose-seductive-invitation', 'env-private-loft', 'light-editorial'],
  },

  // LEVEL 10-12: NIGHT OF PASSION (PRIMARY RANGE)
  {
    id: 'concept-boudoir-passion',
    category: 'concept',
    name: 'Boudoir Passion',
    abbreviation: 'BOUD',
    icon: '🌹',
    color: '#C084FC',
    shape: 'circle',
    effects: {
      intimacy: [10, 12],
      seduction: [11, 13],
      eroticism: [11, 13],
      professionalism: [10, 12],
      boundary: [10, 12],
    },
    description: 'Intimate boudoir with lace teddy, soft sensual lighting, night of passion aesthetic',
    compatibleWith: ['subject-super-seductress', 'wardrobe-lace-teddy', 'pose-seductive-invitation', 'env-boudoir', 'light-chiaroscuro', 'weave-passion'],
  },
  {
    id: 'concept-midnight-seduction',
    category: 'concept',
    name: 'Midnight Seduction',
    abbreviation: 'MIDN',
    icon: '🌙',
    color: '#C084FC',
    shape: 'circle',
    effects: {
      intimacy: [11, 13],
      seduction: [12, 14],
      eroticism: [12, 14],
      professionalism: [11, 13],
      power: [10, 12],
      boundary: [11, 13],
    },
    description: 'Super-Seductress in open satin robe, dramatic shadow play, lustful expression',
    compatibleWith: ['subject-super-seductress', 'wardrobe-satin-robe', 'pose-passionate-expression', 'env-boudoir', 'light-shadow-play', 'weave-passion'],
  },
  {
    id: 'concept-leather-dominance',
    category: 'concept',
    name: 'Leather Dominance',
    abbreviation: 'LEAT',
    icon: '🔥',
    color: '#C084FC',
    shape: 'circle',
    effects: {
      intimacy: [11, 13],
      seduction: [12, 14],
      eroticism: [12, 14],
      professionalism: [11, 13],
      power: [14, 16],
      boundary: [11, 13],
    },
    description: 'Strappy leather set, bold chiaroscuro, power dynamics and seduction merged',
    compatibleWith: ['subject-super-seductress', 'wardrobe-strappy-set', 'pose-passionate-expression', 'env-private-loft', 'light-chiaroscuro', 'weave-passion', 'style-newton'],
  },

  // LEVEL 12-14: BOLD SEDUCTION
  {
    id: 'concept-fishnet-fantasy',
    category: 'concept',
    name: 'Fishnet Fantasy',
    abbreviation: 'FISH',
    icon: '🕸️',
    color: '#D8B4FE',
    shape: 'circle',
    effects: {
      intimacy: [12, 14],
      seduction: [13, 15],
      eroticism: [13, 15],
      professionalism: [12, 14],
      boundary: [12, 14],
    },
    description: 'Geometric fishnet bodysuit, intimate close-ups, bold erotic art aesthetic',
    compatibleWith: ['subject-super-seductress', 'wardrobe-fishnet-bodysuit', 'pose-passionate-expression', 'env-private-loft', 'light-chiaroscuro', 'weave-intimate', 'style-newton'],
  },
  {
    id: 'concept-chain-goddess',
    category: 'concept',
    name: 'Chain Goddess',
    abbreviation: 'GODE',
    icon: '⛓️',
    color: '#D8B4FE',
    shape: 'circle',
    effects: {
      intimacy: [13, 15],
      seduction: [13, 15],
      eroticism: [13, 15],
      professionalism: [13, 15],
      abstraction: [14, 16],
      boundary: [13, 15],
    },
    description: 'Chain drape system creating liquid metal effect, sculptural abstraction',
    compatibleWith: ['subject-super-seductress', 'wardrobe-chain-drape', 'pose-passionate-expression', 'env-private-loft', 'light-shadow-play', 'weave-intimate', 'style-newton'],
  },

  // LEVEL 14-16: CINEMATIC SEDUCTION
  {
    id: 'concept-temple-jewels',
    category: 'concept',
    name: 'Temple Jewels',
    abbreviation: 'JEWE',
    icon: '💎',
    color: '#E9D5FF',
    shape: 'circle',
    effects: {
      intimacy: [14, 16],
      seduction: [15, 17],
      eroticism: [15, 17],
      professionalism: [16, 18],
      abstraction: [15, 17],
      boundary: [14, 16],
    },
    description: 'Traditional temple jewelry as primary coverage, sacred art tradition meets sensuality',
    compatibleWith: ['subject-super-seductress', 'wardrobe-temple-jewelry', 'pose-sacred-positioning', 'env-sacred-space', 'light-sacred', 'weave-seductive', 'style-khajuraho'],
  },
  {
    id: 'concept-body-art',
    category: 'concept',
    name: 'Body Art Masterwork',
    abbreviation: 'BODY',
    icon: '🎨',
    color: '#E9D5FF',
    shape: 'circle',
    effects: {
      intimacy: [15, 17],
      seduction: [15, 17],
      eroticism: [15, 17],
      professionalism: [17, 19],
      abstraction: [17, 19],
      boundary: [15, 17],
    },
    description: 'Intricate body painting as wardrobe, fine art photography tradition',
    compatibleWith: ['subject-super-seductress', 'wardrobe-body-paint', 'pose-sacred-positioning', 'env-sacred-space', 'light-sacred', 'weave-seductive', 'style-fine-art'],
  },

  // SUPER-SEDUCTRESS SIGNATURE CONCEPTS
  {
    id: 'concept-corporate-to-erotic',
    category: 'concept',
    name: 'Corporate to Erotic',
    abbreviation: 'C2E',
    icon: '🎭',
    color: '#A855F7',
    shape: 'circle',
    effects: {
      intimacy: [8, 12],
      seduction: [10, 14],
      eroticism: [9, 13],
      professionalism: [8, 12],
      power: [12, 16],
      boundary: [9, 13],
    },
    description: 'Bi-polar transition: corporate dominance to vulnerable erotic-muse (Super-Seductress signature)',
    compatibleWith: ['subject-super-seductress', 'wardrobe-blazer-bodysuit', 'pose-seductive-invitation', 'env-corporate', 'light-chiaroscuro', 'weave-passion'],
  },
  {
    id: 'concept-power-to-surrender',
    category: 'concept',
    name: 'Power to Surrender',
    abbreviation: 'P2S',
    icon: '⚖️',
    color: '#9333EA',
    shape: 'circle',
    effects: {
      intimacy: [10, 14],
      seduction: [12, 16],
      eroticism: [11, 15],
      professionalism: [11, 15],
      power: [10, 18], // Bi-polar range
      boundary: [10, 14],
    },
    description: 'Dynamic power shift from dominance to vulnerable intimacy (Super-Seductress bi-polar range)',
    compatibleWith: ['subject-super-seductress', 'wardrobe-strappy-set', 'pose-passionate-expression', 'env-boudoir', 'light-shadow-play', 'weave-seductive', 'style-brass'],
  },

  // RIVAL SEDUCTRESS CONCEPTS (Competitive Energy)
  {
    id: 'concept-rival-challenge',
    category: 'concept',
    name: 'Rival Challenge',
    abbreviation: 'RIVL',
    icon: '⚔️',
    color: '#7C3AED',
    shape: 'circle',
    effects: {
      intimacy: [9, 11],
      seduction: [11, 13],
      eroticism: [10, 12],
      professionalism: [10, 12],
      power: [13, 15],
      boundary: [9, 11],
    },
    description: 'Competitive seductress energy, bold pose, assertive power dynamic',
    compatibleWith: ['subject-seductress', 'wardrobe-cutout-bodysuit', 'pose-seductive-invitation', 'env-private-loft', 'light-editorial', 'weave-passion'],
  },
  {
    id: 'concept-dual-goddesses',
    category: 'concept',
    name: 'Dual Goddesses',
    abbreviation: 'DUAL',
    icon: '👯',
    color: '#7C3AED',
    shape: 'circle',
    effects: {
      intimacy: [11, 13],
      seduction: [12, 14],
      eroticism: [12, 14],
      professionalism: [12, 14],
      power: [11, 13],
      boundary: [11, 13],
    },
    description: 'Seductress and Super-Seductress together, mirror dynamics, competitive allure',
    compatibleWith: ['subject-super-seductress', 'wardrobe-geometric-harness', 'pose-passionate-expression', 'env-private-loft', 'light-chiaroscuro', 'weave-passion', 'style-newton'],
  },

  // STEAM ROOM / SPA CONCEPTS
  {
    id: 'concept-steam-goddess',
    category: 'concept',
    name: 'Steam Room Goddess',
    abbreviation: 'STEA',
    icon: '💨',
    color: '#8B5CF6',
    shape: 'circle',
    effects: {
      intimacy: [11, 13],
      seduction: [11, 13],
      eroticism: [11, 13],
      professionalism: [11, 13],
      boundary: [11, 13],
    },
    description: 'Humid spa environment, perspiration effects, oils and water on curves',
    compatibleWith: ['subject-seductress', 'wardrobe-silk-slip', 'pose-seductive-invitation', 'env-boudoir', 'light-studio-soft'],
  },

  // NATURAL PARADISE CONCEPTS
  {
    id: 'concept-forest-curves',
    category: 'concept',
    name: 'Forest Curves',
    abbreviation: 'FORE',
    icon: '🌲',
    color: '#8B5CF6',
    shape: 'circle',
    effects: {
      intimacy: [9, 11],
      seduction: [9, 11],
      eroticism: [9, 11],
      professionalism: [10, 12],
      abstraction: [10, 12],
      boundary: [9, 11],
    },
    description: 'Misty woods, natural curved features echoing bombshell curves',
    compatibleWith: ['subject-seductress', 'wardrobe-mesh-panel', 'pose-seductive-invitation', 'env-private-loft', 'light-studio-soft'],
  },
];

export default seductressConceptNodes;
